version: '3.8'

services:

  web:
    volumes:      
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/wp-content/themes:/var/www/html/wp-content/themes:cached

  wordpress:
    build:    
      dockerfile: ./wordpress/Dockerfile.dev
    volumes:      
      - ./src/wp-content/themes:/var/www/html/wp-content/themes:cached
      - ./wordpress/wp-php.ini:/usr/local/etc/php/conf.d/wp-php.ini
      - ./wordpress/xdebug.php.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      # - ./profiling:/opt/profiling

    environment:
      WORDPRESS_DEBUG: 1
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);              

  adminer:
    container_name: ${SITE}-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8088:8080

volumes:
  db_data:
  wp_data:
